
services:
  backend:
    networks:
      - backend
    container_name: post-backend
    build: 
      context: backend
      dockerfile: Dockerfile
    image: opti-backend
    ports:
      - 4000:3000  
    depends_on:
      - postgres
    env_file:
      - .env
  frontend:
    networks:
      - frontend
    container_name: post-frontend
    build: 
      context: frontend
      dockerfile: Dockerfile
    image: opti-frontend
    ports:
      - 8080:80
  postgres:
    networks:
      - backend
    container_name: postgres
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
  adminer: 
    networks:
      - backend
    container_name: adminer
    image: adminer
    ports:
      - 8081:8080

volumes: 
  postgres_data:

networks:
  frontend:
  backend: